### ISSUE TITLE
npr.Story() doesn't work

### ISSUE THREAD

**Issue by jpzhangvincent** [perrydc/npr#23]
I followed the example in the tutorial but failed to reproduce the result. Any thoughts? Thanks!
![image](https://user-images.githubusercontent.com/7220686/39147292-175936ee-46ee-11e8-8a76-175a06acdbce.png)

**Comment by perrydc** [comment]
Sorry jpzhangvincent!  This used to work, but for security reasons we had to deprecate support for this service for public keys.  I've removed the confusing documentation and added a ticket to reinstate this functionality in the SDK once our devs resolve the security issue.
